# FinCommerce Application Configuration

server.port=8085
spring.application.name=FinCommerce Backend

# PostgreSQL / Supabase Configuration Example:
# spring.datasource.url=jdbc:postgresql://db.xxxx.supabase.co:5432/postgres
# spring.datasource.username=postgres
# spring.datasource.password=YOUR_SUPABASE_PASSWORD
# spring.datasource.driver-class-name=org.postgresql.Driver
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# H2 In-Memory Database (Default for zero-dependency instant local execution & testing)
spring.datasource.url=jdbc:postgresql://aws-0-ap-southeast-2.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.driverClassName=org.postgresql.Driver
spring.datasource.username=postgres.wnolgoiwozymdrqiawua
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.password=fristprojectsuba
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA / Hibernate Configuration
spring.jpa.show-sql=false
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.format_sql=true

# JWT Security Configurations
app.jwt.secret=9a2f8c4e1b7d5a0f3e6c9b2a5d8f1e4c7b0a3f6e9d2c5b8a1f4e7d0c3b6a9f2e
app.jwt.expiration-milliseconds=86400000

# File Upload Limit
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
